# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af57c1652f299287ea7a588f08102fdd4c83121c062811615bf48f2250b3ec6f96e385b1d19c3bf3ed2b3b59dd0e7dfea4f63c2b091bcaba11df59dd3eab85b5

test:
  secret_key_base: 59bb1c9a7b29803ea6bae3d8d2f85621e80c7d4c03da735606ff5f490568eb6266c86443ebad13c0ac23509e19e644676bcebe1922f14150d590439dc893edac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
